apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned:
    crlDistributionPoints:
      - "*.${DP_EP}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mw-credential
  namespace: istio-system
spec:
  secretName: mw-credential
  commonName: "${DP_EP}"
  issuerRef:
    name: selfsigned-issuer
  dnsNames:
    - "*.${DP_EP}"
