apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: pv-${VOLUMEID}
spec:
  capacity:
    storage: "${OS_VOLUME_SIZE}"
  storageClassName: "${K8S_STORAGECLASS}"
  persistentVolumeReclaimPolicy: "Retain"
  accessModes:
    - "ReadWriteOnce"
  cinder:
    fsType: "ext4"
    volumeID: "${VOLUMEID}"
